name: Report a bug
description: Report a bug in binsync
labels: [bug,needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit this bug report!

        Before submitting this bug report, please check the following, which may resolve your issue:
        * Have you checked that you are running the latest versions of BinSync and its components? BinSync is rapidly-evolving!
        * Have you [searched existing issues](https://github.com/binsync/binsync/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this bug has been reported before?
        * Have you checked the [documentation](https://binsync.net/docs/home/)?

        Please note: The BinSync suite is maintained by a small team. While we cannot guarantee any timeliness for fixes and enhancements, we will do our best. For more real-time help with BinSync, from us and the community, join our [Discord](https://discord.gg/wZSCeXnEvR).

  - type: textarea
    attributes:
      label: Description
      description: Brief description of the bug, with any relevant log messages.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce the bug
      description: |
        If appropriate, include screenshots, and if possible **attach the binary used**.

        **Tip:** You can attach files to the issue by first clicking on the textarea to select it, then dragging & dropping the file onto the textarea.
  - type: textarea
    attributes:
      label: Environment
      description: Many common issues are caused by problems with the local Python environment. Before submitting an issue confirm that you are using the same Python environment as your decompiler.

  - type: textarea
    attributes:
      label: Additional context
      description: Any additional context about the problem.
