blank_issues_enabled: false
contact_links:
  - name: Join our Discord community
    url: https://discord.gg/wZSCeXnEvR
    about: For questions and help with BinSync, you are invited to join the BinSync Discord community
