name: Request a feature
description: Request a new feature for binsync
labels: [enhancement,needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit this feature request!

        Before submitting this feature request, please check the following:
        * Have you checked that you are running the latest versions of BinSync and its components? BinSync is rapidly-evolving!
        * Have you [searched existing issues](https://github.com/binsync/binsync/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this bug has been reported before?
        * Have you checked the [documentation](https://binsync.net/docs/home/)?

        Please note: The BinSync suite is maintained by a small team. While we cannot guarantee any timeliness for fixes and enhancements, we will do our best. For more real-time help with BinSync, from us and the community, join our [Discord](https://discord.gg/wZSCeXnEvR).

  - type: textarea
    attributes:
      label: Description
      description: |
        Brief description of the desired feature. If the feature is intended to solve some problem, please clearly describe the problem, including any relevant binaries, etc.

        **Tip:** You can attach files to the issue by first clicking on the textarea to select it, then dragging & dropping the file onto the textarea.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description: Possible alternative solutions or features that you have considered.

  - type: textarea
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request.
