name: Ask a question
description: Ask a question about binsync
labels: [question,needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        If you have a question about binsync, that is not a bug report or a feature request, you can ask it here. For more real-time help with binsync, from us and the community, join our [Discord](https://discord.gg/wZSCeXnEvR).

        Before submitting this question, please check the following, which may answer your question:
        * Have you checked the [documentation](https://binsync.net/docs/home/)?
        * Have you [searched existing issues](https://github.com/binsync/binsync/issues?q=is%3Aissue+label%3Aquestion) to see if this question has been answered before?
        * Have you checked that you are running the latest versions of BinSync and its components? BinSync is rapidly-evolving!

        Please note: The BinSync suite is maintained by a small team. While we cannot guarantee any timeliness for fixes and enhancements, we will do our best. For more real-time help with BinSync, from us and the community, join our [Discord](https://discord.gg/wZSCeXnEvR).

  - type: textarea
    attributes:
      label: Question
      description:
    validations:
      required: true
