name: Ghidra Extension Build

env:
  ghidra-url: https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.3_build/ghidra_10.3_PUBLIC_20230510.zip
  ghidra-zip-filename: ghidra_10.3_PUBLIC.zip
  ghidra-directory: ghidra_10.3_PUBLIC

on:
  workflow_run:
    workflows: [ "Release" ]
    types:
      - completed
  pull_request:
    branches: [ main ]
    paths: ['binsync/decompilers/ghidra/**']
  push:
    branches: [ main ]
    paths: ['binsync/decompilers/ghidra/**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download Ghidra release
      uses: carlosperate/download-file-action@v1.0.3
      id: download-ghidra
      with:
        file-url: ${{ env.ghidra-url }}
        file-name: ${{ env.ghidra-zip-filename }}

    - name: Unzip Ghidra
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq ${{ steps.download-ghidra.outputs.file-path }} -d .
    - uses: actions/setup-java@v1
      with:
        java-version: '17.0.6'

    - name: Build extension
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: '7.3'
        build-root-directory: ${{ github.workspace }}/binsync/decompilers/ghidra/client/
        arguments: '-PGHIDRA_INSTALL_DIR=${{ github.workspace }}/${{ env.ghidra-directory }}'

    - name: Rename extension
      run: cd binsync/decompilers/ghidra/client/dist/ && mv *.zip binsync-ghidra-plugin.zip
    - name: Upload built extension
      uses: actions/upload-artifact@v2
      with:
        name: extension
        path: binsync/decompilers/ghidra/client/dist/binsync-ghidra-plugin.zip

  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_run' }}
    needs: build

    steps:
    - name: Download built extension
      uses: actions/download-artifact@v2
      with:
        name: extension
    - name: Upload To Github Release
      uses: xresloader/upload-to-github-release@v1.3.12
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "*.zip"
        update_latest_release: true
