name: GUI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Set branch name
      run: echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        ./tests/ci/setup_gui_ci.sh

    - name: Pytest
      env:
        QT_QPA_PLATFORM: "offscreen"
      run: |
        QT_QPA_PLATFORM="offscreen" pytest ./tests/test_angr_gui.py -s
