name: GUI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        sudo apt-get install libegl1 -y
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install angr-management
        AM_INSTALL=$(dirname $(python3 -c "import angrmanagement; print(angrmanagement.__file__)"))
        pip install -e .
        binsync --install-angr-only $AM_INSTALL 

    - name: Pytest
      env:
        QT_QPA_PLATFORM: "offscreen"
      run: |
        pytest ./tests/test_angr_gui.py
