name: GUI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        sudo apt-get install libegl1 -y
        sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
        python -m pip install --upgrade pip
        pip install angr-management flake8 pytest pyside6
        AM_INSTALL=$(dirname $(python3 -c "import angrmanagement; print(angrmanagement.__file__)"))
        pip install -e .[test]
        binsync --install-angr-only $AM_INSTALL 

    - name: Pytest
      env:
        QT_QPA_PLATFORM: "offscreen"
      run: |
        QT_QPA_PLATFORM="offscreen" pytest ./tests/test_angr_gui.py -s
