name: Release

on:
  push:
    tags:
    - "v**"

jobs:

  release-github:
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download Plugin
        run: wget "https://github.com/mahaloz/binsync-ghidra-plugin/releases/latest/download/binsync-ghidra-plugin.zip"
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "binsync-ghidra-plugin.zip"

  release-pypi:
    name: Release pypi package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install build
      run: pip install build
    - name: Build dists
      run: python -m build
    - name: Release to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
